const movies = [
  {
    title: 'Ilha do Medo',
    subtitle: 'Shutter Island',
    storyline: "Em 1945 um marechal dos Estados Unidos investia a disaparição dum assassino que escapou um hospital psiquiátrico.",
    rating: 4.8,
    imagePath: 'images/shutterisland.jpg',
    bookmarked: true,
    genre: 'drama',
  },
  {
    title: 'A Origem',
    subtitle: 'Inception',
    storyline: 'Um ladrão que rouba segredos corporativos através do uso de tecnologia é dado a tarefa inversa de plantar uma idéia na mente de um C.E.O.',
    rating: 4.9,
    imagePath: 'images/inception.jpg',
    bookmarked: true,
    genre: 'ficção científica',
  },
  {
    title: 'Bastardos Inglórios',
    subtitle: 'Inglourious Basterds',
    storyline: 'Um plano para assassinar líderes nazistas na França, e liderada por um grupo de soldados judaicos dos Estados Unidos os quais coincidem com os planos vingativos de um dono de teatro.',
    rating: 5,
    imagePath: 'images/inglorious.jpg',
    bookmarked: false,
    genre: 'guerra',
  },
  {
    title: 'Django Livre',
    subtitle: 'Django Unchained',
    storyline: "Com a ajuda de um caçador de recompensas alemão, um escravo libertado sai para resgatar sua esposa de um brutal dono de uma plantação no Mississipi.",
    rating: 4.8,
    imagePath: 'images/django.jpg',
    bookmarked: true,
    genre: 'faroeste',
  },
  {
    title: 'Top Gang 2',
    subtitle: 'Hot Shots 2',
    storyline: 'Paródia de "Rambo" na qual Topper Harley lidera uma equipe de resgate no Iraque para salvar prisioneiros de guerra iraquianos e todas as suas equipes de resgate anteriores.',
    rating: 4.2,
    imagePath: 'images/topgang.jpeg',
    bookmarked: false,
    genre: 'comédia',
  },
  {
    title: 'Coringa',
    subtitle: 'Joker',
    storyline: 'Um comediante falido enlouquece e se torna um assassino psicopata.',
    rating: 4.7,
    imagePath: 'images/joker.jpeg',
    bookmarked: false,
    genre: 'drama',
  },
  {
    title: '1917',
    subtitle: 'Inglourious Basterds',
    storyline: 'A vida de milhares de soldados está na mão de apenas dois jovens durante a primeira guerra mundial.',
    rating: 5,
    imagePath: 'images/1917.jpeg',
    bookmarked: true,
    genre: 'guerra',
  },
  {
    title: 'Os Infiltrados',
    subtitle: 'The departed',
    storyline: 'Um policial disfarçado e um espião estão tentando se identificar enquanto se infiltram em uma gangue irlandesa no sul de Boston.',
    rating: 4.5,
    imagePath: 'images/infiltrados.jpeg',
    bookmarked: false,
    genre: 'drama',
  },
  {
    title: 'Ex-Machina: Instinto Artificial',
    subtitle: 'Ex-Machina',
    storyline: 'Um jovem programador é seleccioãdo para participar num experimento com inteligença sintética.',
    rating: 4.5,
    imagePath: 'images/exmachina.jpeg',
    bookmarked: true,
    genre: 'ficção científica',
  },
];

export default movies;
